## Hello guys! Welcome to Day-3 of the sessions. Hope you were able to do day2 task and didn't face any issues. In case you do, please make sure to put them up on the issues tab.

### Lets begin with this session right away!

# Part-1 NumPy Basics

In [1]:
import numpy as np

## Create NumPy array

In [2]:
## Creating array using a list
ls1 = [1, 3, 4, 5] ## 1 dimensional list
arr1 = np.array(ls1)
print(arr1)

ls2 = [[1, 2, 3, 4],[6, 7, 8, 9]] ## Multi-dimensional list
data = np.array(ls2) ## creating a NumPy array
print(data)

print(data.ndim) 
print(data.shape)
print(data.dtype) 

[1 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
2
(2, 4)
int64


In [3]:
## Array of zeros
arr2 = np.zeros(5)
arr3 = np.zeros((1,5))
## Note the difference in shape of arr2 and arr3
arr4 = np.zeros((4,5)) ## higher dimensional array with 0s
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)

(5,)
(1, 5)
(4, 5)


In [4]:
#empty creates an array without initializing its values to any particular value.
np.empty((4, 2, 2))

array([[[2.21604466e-314, 2.21128386e-314],
        [2.23816277e-314, 2.21072555e-314]],

       [[2.21088795e-314, 2.21081279e-314],
        [2.68156159e+154, 2.68156159e+154]],

       [[4.44659081e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 4.94065646e-324],
        [4.94065646e-324, 0.00000000e+000]]])

Let's figure out some more stuff from table below
![](Images/arr2.png)
![](images/arr1.png)

### Data Types for ndarrays
The data type or dtype is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data

In [5]:
ls = [[1, 2, 3, 4],[6, 7, 8, 9]]
arr1 = np.array(ls, dtype=np.float64)
print(arr1.dtype)
print(arr1)

float64
[[1. 2. 3. 4.]
 [6. 7. 8. 9.]]


The numerical dtypes are named the same way: a type name, like float or int, followed by a number indicating the number of bits per element. `Checkout table below for more information`
![](Images/arr4.png)
![](images/arr3.png)

In [6]:
## You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:
## Int ------> float
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

## Float ------> Int
## If I cast some floating point numbers to be of integer dtype, the decimal part will be truncated:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

## You can also use another array’s dtype attribute:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(int_array.astype(calibers.dtype))

int64
float64
[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [7]:
## If you have an array of strings representing numbers, you can use astype to convert them to numeric form:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))
## If casting were to fail for some reason (like a string that cannot be converted to float64), a TypeError will be raised

[ 1.25 -9.6  42.  ]


## Operations between Arrays and Scalars
Arrays are important because they enable you to express batch operations on data `without writing any for loops.` This is usually called `vectorization`. Any arithmetic op- erations between equal-size arrays applies the operation elementwise:

In [8]:
ls = [[1, 2, 3, 4],[6, 7, 8, 9]]
arr = np.array(ls)
print(arr*arr)
print(arr-arr)
print(arr/arr)
print(1/arr)
print(arr**2)

[[ 1  4  9 16]
 [36 49 64 81]]
[[0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.         0.5        0.33333333 0.25      ]
 [0.16666667 0.14285714 0.125      0.11111111]]
[[ 1  4  9 16]
 [36 49 64 81]]


Operations between differently sized arrays is called `broadcasting` and will be discussed in more detail in later in this notebook

## Basic Indexing and Slicing
![](Images/arr5.png)

In [9]:
ls = [[1, 2, 3, 4],[6, 7, 8, 9]]
arr = np.array(ls)
print(arr)
print(arr[1][3])
## or use 
print(arr[1, 3])

[[1 2 3 4]
 [6 7 8 9]]
9
9


**`Array slices are views on the original array.` This means that the data is not copied, and any modifications to the view will be reflected in the source array**

In [10]:
arr = np.arange(7)
print(arr[3: 6])

arr[5:7] = 12 ##the value is propagated (or broadcasted henceforth) to the entire selection
print(arr)

[3 4 5]
[ 0  1  2  3  4 12 12]


**If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array; for example arr[5:7].copy().**

In [11]:
ls = [[1, 2, 3, 4],[6, 7, 8, 9]]
arr = np.array(ls)
print(arr)
print(arr[:2, 1:])

[[1 2 3 4]
 [6 7 8 9]]
[[2 3 4]
 [7 8 9]]


![](Images/arr6.png)

In [12]:
## Lets involve bool values as well
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
bool1 = names == 'Will'
data[bool1, 2:4]

[[-0.84227915 -1.14157353  0.03190473  0.70181277]
 [-0.27517546  0.51079121  0.45943045 -0.17141814]
 [ 1.28230859  2.71872714 -1.77469212 -1.04371614]
 [-0.19137008  1.62939369  0.04743762  0.06760603]
 [-1.00810587 -2.01344712  1.18277405 -0.48646892]
 [-1.02771985 -0.04337816  0.70244929  0.93993964]
 [ 1.43459733  0.73883664 -0.68659771  0.42040738]]


array([[-1.77469212, -1.04371614],
       [ 1.18277405, -0.48646892]])

In [13]:
## Some Fancy indexing
print(data[[6, -2, -1], [0, 3, 2]])
data[[6, -2, -1]][:, [0, 3, 2]]

[ 1.43459733  0.93993964 -0.68659771]


array([[ 1.43459733,  0.42040738, -0.68659771],
       [-1.02771985,  0.93993964,  0.70244929],
       [ 1.43459733,  0.42040738, -0.68659771]])

**`Note:`** ***Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.***

## Transposing Arrays and Swapping Axes
Transposing is a special form of reshaping which similarly returns a view on the underlying data `without copying anything.`

In [14]:
arr = np.arange(15).reshape((3, 5))
print(arr, '\n')
print(arr.T, '\n')


arr = np.arange(16).reshape((2, 2, 4))
print(arr, '\n')
print(arr.T, '\n')
print(arr.swapaxes(0,1), '\n') ## simply swap 2 axis 
print(arr.transpose((1,0,2)), '\n') ## can swap multiple axis at a time

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]] 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] 



## Universal Functions: Element-wise Array Functions

In [15]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(np.sqrt(arr))
print(np.exp(arr))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]


![](Images/arr7.png)
![](Images/arr8.png)

In [16]:
arr1 = np.arange(0, 7, 0.01)
arr2 = np.arange(0, 2, 0.1)
np.meshgrid(arr1, arr2) ## produces all possible combination between arr1 and arr2

[array([[0.  , 0.01, 0.02, ..., 6.97, 6.98, 6.99],
        [0.  , 0.01, 0.02, ..., 6.97, 6.98, 6.99],
        [0.  , 0.01, 0.02, ..., 6.97, 6.98, 6.99],
        ...,
        [0.  , 0.01, 0.02, ..., 6.97, 6.98, 6.99],
        [0.  , 0.01, 0.02, ..., 6.97, 6.98, 6.99],
        [0.  , 0.01, 0.02, ..., 6.97, 6.98, 6.99]]),
 array([[0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1],
        [0.2, 0.2, 0.2, ..., 0.2, 0.2, 0.2],
        ...,
        [1.7, 1.7, 1.7, ..., 1.7, 1.7, 1.7],
        [1.8, 1.8, 1.8, ..., 1.8, 1.8, 1.8],
        [1.9, 1.9, 1.9, ..., 1.9, 1.9, 1.9]])]

## Sorting

NumPy arrays can be sorted `in-place using the sort method`,meaning that the array contents are rearranged without producing a new array.
The top level method np.sort returns a `sorted copy of an array` instead of modifying the array in place.

In [17]:
arr = np.array([[2, 5, 100, 4],[153, 62, 37, 82]])
np.sort(arr)

array([[  2,   4,   5, 100],
       [ 37,  62,  82, 153]])

In [18]:
## using sort method
arr.sort()

### Indirect Sorts: argsort and lexsort

In [19]:
values = np.array([5, 0, 1, 3, 2]) 
indexer = values.argsort()
print(indexer)
values[indexer] 

[1 2 4 3 0]


array([0, 1, 2, 3, 5])

In [20]:
## lexsort is similar to argsort, but it performs an indirect lexicographical sort on multiple key arrays.
first_name = np.array([22, 11, 45, 2]) 
last_name = np.array([34, 43, 2, 32]) 
sorter = np.lexsort((first_name, last_name))
print(first_name[sorter])
(last_name[sorter])

[45  2 22 11]


array([ 2, 32, 34, 43])

## Unique and Set logic

Try to implement stuff below by creating new cell
![](Images/arr9.png)

## Random Number Generation
The numpy.random module supplements the built-in Python random with functions for efficiently generating whole arrays of sample values from many kinds of probability
distributions

See Table 4-8 for a partial list of functions available in numpy.random.
![](Images/arr10.png)

## Vectorization
Vectorization is used to speed up the Python code without using loop. Using such a function can help in minimizing the running time of code efficiently.
To do so, Python has some standard mathematical functions for fast operations on entire arrays of data without having to write loops. One of such library which contains such function is `numpy.`

Refer some functions for implementing vectorization in numpy
![](Images/arr15.png)

### Matrix Multiplication
Various operations are being performed over vector such as: 
<ol>
    <li>dot product of vectors which is also known as scalar product as it produces single output</li>
<li>outer products which results in square matrix of dimension equal to length X length of the vectors</li>
<li>Element wise multiplication which products the element of same indexes and dimension of the matrix remain unchanged.</li>
</ol>

In [21]:
## Matrix multiplication using dot is same as matrix multiplication in maths
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(x.dot(y))
## or use this
np.dot(x, y)

[[ 28.  64.]
 [ 67. 181.]]


array([[ 28.,  64.],
       [ 67., 181.]])

In [22]:
## For elementwise multiplication
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23., 9], [-1, 7, 8]])
print(np.multiply(x, y))

## Equivalent to x1 * x2 in terms of array broadcasting.
x*y

[[ 6. 46. 27.]
 [-4. 35. 48.]]


array([[ 6., 46., 27.],
       [-4., 35., 48.]])

# Part-2 Advanced NumPy

## Reshaping Arrays
Given what we know about NumPy arrays, it should come as little surprise that you can convert an array from one shape to another `without copying any data.`

In [23]:
arr = np.arange(20)
arr = arr.reshape((5,4))
print(arr)
## Reshape from hifher dimension to 1 dimension is called revelling or flattening
print(arr.flatten())
print(arr.ravel())
# fatten method behaves similar to ravel except it always return a copy of data

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## C versus Fortran Order
NumPy arrays are created in row major order. Spatially this means that if you have a two-dimensional array of data, the items in each row of the array are stored in adjacent memory locations. The alternative to row major ordering is column major order, which means that (you guessed it) values within each column of data are stored in adjacent memory locations.
![](Images/arr11.png)

In [24]:
print(arr.ravel('F')) ## F argument for column major
print(arr.flatten('C')) ## C argument for row major

[ 0  4  8 12 16  1  5  9 13 17  2  6 10 14 18  3  7 11 15 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Concating and Splitting Arrays

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) 
arr2 = np.array([[7, 8, 9], [10, 11, 12]]) 
print(np.concatenate([arr1, arr2], axis=0)) ## along row axis
print(np.concatenate([arr1, arr2], axis=1)) ## along column axis

arr3 = np.arange(20).reshape((5,4))
a1, a2, a3 = np.split(arr3, [1, 3]) ## putting cuts at 1st and 3rd posion along axis=0
print(a1)
print(a2)
print(a3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]]


See Table 12-1 for a list of all relevant concatenation and splitting functions, some of which are provided only as a convenience of the very general purpose concatenate.
![](Images/arr12.png)

## Fancy Indexing Equivalents: Take and Put

In [26]:
arr = np.arange(10) * 100
inds = inds = [7, 1, 2, 6]
print(arr.take(inds))

arr.put(inds, 42)
print(arr)
## As of this writing, the take and put functions in general have better performance than their fancy indexing equivalents by a significant margin

[700 100 200 600]
[  0  42  42 300 400 500  42  42 800 900]


## Broadcasting

See Figure 12-4, 12-5 for an illustration of this operation
![](Images/arr13.png)
![](Images/arr14.png)

In [27]:
arr = np.random.rand(4, 3)
print(arr.mean(0))
demeaned = arr - arr.mean(0)
demeaned

[0.3500735  0.51786308 0.43407086]


array([[-0.19337549,  0.24368272, -0.37190765],
       [-0.08064782, -0.47651892,  0.42202741],
       [-0.138895  ,  0.1312184 ,  0.17296499],
       [ 0.41291832,  0.10161779, -0.22308475]])

In [28]:
## Setting arr value using broadcastimg
arr = np.empty((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

## Structured Arrays
A structured array is an ndarray in which each element can be thought of as representing a struct in C (hence the “structured” name) or a row in a SQL table with multiple named fields

Since each element in the array is represented in memory as a fixed number of bytes, structured arrays provide a very fast and efficient way of writing data to and from disk, transporting it over the network, and other such use.

In [29]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
print(sarr)
print(sarr[0])
print(sarr[0]['y'])
print(sarr['x'])

[(1.5       ,  6) (3.14159265, -2)]
(1.5, 6)
6
[1.5        3.14159265]


## Performance Tips
Getting good performance out of code utilizing NumPy is often straightforward, as array operations typically replace otherwise comparatively extremely slow pure Python loops. Here is a brief list of some of the things to keep in mind:
<ol>
    <li>Convert Python loops and conditional logic to array operations and boolean array operations</li>
    <li>Use broadcasting whenever possible</li>
    <li>Avoid copying data using array views (slicing)</li>
</ol>

### The Importance of Contiguous memory
Operations accessing contiguous blocks of memory (for example, summing the rows of a C order array) will generally be the fastest because 
<ol>
<li>The memory subsystem will buffer the appropriate blocks of memory into the ultrafast L1 or L2 CPU cache.</li>
    <li>Also, certain code paths inside NumPy’s C codebase have been optimized for the contiguous case in which generic strided memory access can be avoided.</li>
</ol>

To say that an array’s memory layout is contiguous means that the elements are stored in memory in the order that they appear in the array with respect to Fortran (column major) or C (row major) ordering. These properties can be ex- plicitly checked via the flags attribute on the ndarray:

In [30]:
arr_c = np.ones((1000, 1000), order='C') 
arr_f = np.ones((1000, 1000), order='F')
print(arr_c.flags) 
arr_f.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [31]:
%timeit arr_c.sum(1)

433 µs ± 6.61 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
%timeit arr_f.sum(1)

629 µs ± 24.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Congratulations on learning most of concepts of NumPy. Now let's learn about matplotlib.